spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/oauth
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  profiles:
    include: oauth
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false

logging.level:
  org.hibernateSQL : debug

server.servlet.encoding.force-response: true


